#!/usr/bin/env python3
"""Generate src/og-image.ts: a small PNG served at /og.png.

Kept as a script (not a committed blob) so the image can be regenerated after a
palette change. Run: python scripts/gen-og-image.py
"""
import base64
import struct
import zlib
from pathlib import Path

W, H = 1200, 630
BG = (11, 16, 32)
ACCENT = (74, 222, 128)
ACCENT2 = (96, 165, 250)
FG = (232, 236, 248)

# 5x7 bitmap font, enough for the few glyphs the card needs.
FONT = {
    "t": ["11111", "00100", "00100", "00100", "00100", "00100", "00100"],
    "o": ["01110", "10001", "10001", "10001", "10001", "10001", "01110"],
    "r": ["11110", "10001", "10000", "10110", "11001", "10001", "10001"],
    "b": ["11110", "10001", "10001", "11110", "10001", "10001", "11110"],
    "m": ["10001", "11011", "10101", "10001", "10001", "10001", "10001"],
    "c": ["01110", "10001", "10000", "10000", "10000", "10001", "01110"],
    "p": ["11110", "10001", "10001", "11110", "10000", "10000", "10000"],
    "a": ["01110", "10001", "10001", "01111", "10001", "10001", "01111"],
    "i": ["11111", "00100", "00100", "00100", "00100", "00100", "11111"],
    "s": ["01111", "10000", "10000", "01110", "00001", "00001", "11110"],
    "e": ["11111", "10000", "10000", "11110", "10000", "10000", "11111"],
    "n": ["10001", "11001", "10101", "10011", "10001", "10001", "10001"],
    "g": ["01110", "10001", "10001", "01111", "00001", "00001", "01110"],
    "d": ["00001", "00001", "00001", "01111", "10001", "10001", "01111"],
    "v": ["10001", "10001", "10001", "10001", "10001", "01010", "00100"],
    "l": ["00100", "00100", "00100", "00100", "00100", "00100", "01110"],
    "u": ["10001", "10001", "10001", "10001", "10001", "10001", "01110"],
    "y": ["10001", "10001", "10001", "01111", "00001", "00001", "01110"],
    "h": ["10001", "10001", "10001", "11111", "10001", "10001", "10001"],
    "f": ["00111", "01000", "01000", "11110", "01000", "01000", "01000"],
    "k": ["10001", "10010", "10100", "11000", "10100", "10010", "10001"],
    "w": ["10001", "10001", "10001", "10101", "10101", "11011", "10001"],
    "x": ["10001", "10001", "01010", "00100", "01010", "10001", "10001"],
    " ": ["00000", "00000", "00000", "00000", "00000", "00000", "00000"],
    "-": ["00000", "00000", "00000", "11111", "00000", "00000", "00000"],
    ".": ["00000", "00000", "00000", "00000", "00000", "01100", "01100"],
    ":": ["00000", "01100", "01100", "00000", "01100", "01100", "00000"],
}

px = [[BG for _ in range(W)] for _ in range(H)]


def rect(x0, y0, x1, y1, color):
    for y in range(max(0, y0), min(H, y1)):
        for x in range(max(0, x0), min(W, x1)):
            px[y][x] = color


def text(s, x, y, scale, color):
    cx = x
    for ch in s:
        glyph = FONT.get(ch.lower(), FONT[" "])
        for ry, row in enumerate(glyph):
            for rx, bit in enumerate(row):
                if bit == "1":
                    rect(cx + rx * scale, y + ry * scale, cx + (rx + 1) * scale, y + (ry + 1) * scale, color)
        cx += (5 + 1) * scale
    return cx


# Card background, slightly lighter than the page.
rect(0, 0, W, 8, ACCENT)
rect(40, 150, W - 40, H - 150, (20, 26, 48))

text("torob-mcp", 110, 250, 14, ACCENT)
text("iran price comparison", 110, 380, 5, FG)
text("read-only mcp server", 110, 430, 4, ACCENT2)
text("no api key", 110, 480, 4, (154, 166, 200))

raw = b"".join(b"\x00" + bytes(v for p in row for v in p) for row in px)


def chunk(tag, data):
    return struct.pack(">I", len(data)) + tag + data + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)


png = (
    b"\x89PNG\r\n\x1a\n"
    + chunk(b"IHDR", struct.pack(">IIBBBBB", W, H, 8, 2, 0, 0, 0))
    + chunk(b"IDAT", zlib.compress(raw, 9))
    + chunk(b"IEND", b"")
)

b64 = base64.b64encode(png).decode()
out = Path(__file__).resolve().parent.parent / "src" / "og-image.ts"
# Chunked, and decoded with a plain loop rather than Uint8Array.from(str, fn):
# passing a whole multi-kilobyte string through a per-call argument
# conversion truncates it in V8, which produced a 72-byte image.
body = [b64[i : i + 76] for i in range(0, len(b64), 76)]
out.write_text(
    "// Generated by scripts/gen-og-image.py - do not edit by hand.\n"
    "const B64 =\n  '" + "' +\n  '".join(body) + "';\n\n"
    "function decode(b64: string): Uint8Array {\n"
    "  const bin = atob(b64);\n"
    "  const out = new Uint8Array(bin.length);\n"
    "  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);\n"
    "  return out;\n"
    "}\n\n"
    "export const OG_IMAGE = { buffer: decode(B64) };\n",
    encoding="utf-8",
)
print(f"wrote {out} ({len(png)} bytes png, {len(b64)} base64 chars)")
